export const razasPerroFCI = [

  'Pastor Australiano',
  'Kelpie Australiano',
  'Bouvier de las Ardenas',
  'Bouvier de Flandes',
  'Perro de pastor belga Groenendael',
  'Perro de pastor belga Laekenois',
  'Perro de pastor belga Malinois',
  'Perro de pastor belga Tervueren',
  'Perro de pastor de Brie (Briard)',
  'Perro de pastor de Picardía',
  'Bearded Collie',
  'Border Collie',
  'Collie de pelo largo',
  'Collie de pelo corto',
  'Perro de pastor de Bergamo',
  'Perro de pastor de los Abruzos (Maremma)',
  'Perro de pastor de Bohemia',
  'Perro de pastor de Croacia',
  'Perro de pastor de los Cárpatos',
  'Perro de pastor de Macedonia del Norte',
  'Perro de pastor de Polonia de las llanuras',
  'Pastor de Tatras (Podhale)',
  'Perro de pastor holandés',
  'Perro de pastor alemán',
  'Perro de pastor de Cataluña (Gos d\'Atura)',
  'Perro de pastor de Mallorca (Ca de Bestiar)',
  'Perro de pastor del Cáucaso',
  'Perro de pastor de Asia Central',
  'Perro de pastor de Europa del Sur',
  'Perro de pastor de Anatolia (Kangal)',
  'Mudi',
  'Puli',
  'Pumi',
  'Komondor',
  'Kuvasz',
  'Perro de pastor eslovaco de pelo duro',
  'Perro de pastor eslovaco de llanura',
  'Perro de pastor de los Pirineos de cara larga',
  'Perro de pastor de los Pirineos de cara ancha',
  'Perro de pastor de Beauce (Beauceron)',
  'Perro de pastor de la Península Ibérica',
  'Perro de pastor leonés',
  'Perro de pastor de Karst',
  'Perro de pastor montenegrino',
  'Perro de pastor de Serbia',
  'Perro de pastor de Šarplaninac',
  'Pastor de Valée',
  'Perro de pastor rumano de los Cárpatos',
  'Perro de pastor rumano de Mioritic',
  'Perro de pastor rumano de Bucovina',
  'Perro de pastor de Rusia del sur',
  'Saarlooswolfhond',
  'Perro lobo checoslovaco',
  'Perro de pastor blanco suizo',
  'Rottweiler', // también en grupo 2 a veces, pero aquí como boyero
  'Boyero de Appenzell',
  'Boyero de Entlebuch',
  'Gran Boyero suizo',
  'Boyero de Berna',

  // GRUPO 2 - Perros tipo Pinscher y Schnauzer, Molosoides, Perros de montaña y boyeros suizos
  'Dobermann',
  'Pinscher alemán',
  'Pinscher miniatura',
  'Affenpinscher',
  'Schnauzer',
  'Schnauzer miniatura',
  'Schnauzer gigante',
  'Bulldog inglés',
  'Bullmastiff',
  'Mastín inglés',
  'Dogo argentino',
  'Dogo de Burdeos',
  'Dogo del Tíbet',
  'Fila brasileño',
  'Mastín español',
  'Mastín napolitano',
  'Mastín de los Pirineos',
  'Mastín tibetano',
  'Cane Corso',
  'Perro de presa canario (Dogo Canario)',
  'Perro de presa mallorquín (Ca de Bou)',
  'Broholmer',
  'Gran Danés',
  'Hovawart',
  'Landseer',
  'Leonberger',
  'Terranova',
  'San Bernardo',
  'Castro Laboreiro',
  'Cão da Serra da Estrela',
  'Cão de Água português',
  'Rafeiro do Alentejo',
  'Boxer',
  'Perro de montaña del Atlas (Aidi)',
  'Perro de montaña de los Pirineos',
  'Perro de montaña de Bavaria',
  'Perro de montaña de Entlebuch',
  'Perro de montaña de Appenzell',
  'Perro de montaña de Berna',
  'Perro de montaña suizo mayor',
  'Tosa',
  'Akita (japonés)',
  'Akita americano',
  'Perro de Groenlandia',

  // GRUPO 3 - Terriers
  'Airedale Terrier',
  'Australian Terrier',
  'Bedlington Terrier',
  'Border Terrier',
  'Bull Terrier',
  'Bull Terrier miniatura',
  'Cairn Terrier',
  'Dandie Dinmont Terrier',
  'Fox Terrier de pelo duro',
  'Fox Terrier de pelo liso',
  'Glen of Imaal Terrier',
  'Irish Terrier',
  'Kerry Blue Terrier',
  'Lakeland Terrier',
  'Manchester Terrier',
  'Norfolk Terrier',
  'Norwich Terrier',
  'Parson Russell Terrier',
  'Scottish Terrier',
  'Sealyham Terrier',
  'Skye Terrier',
  'Soft Coated Wheaten Terrier',
  'Staffordshire Bull Terrier',
  'Welsh Terrier',
  'West Highland White Terrier',
  'Jack Russell Terrier',
  'Jagdterrier',
  'Terrier alemán de caza',
  'Terrier brasileño',
  'Terrier checo',
  'Terrier de pelo duro eslovaco',
  'Terrier japonés',
  'Terrier negro ruso',
  'Terrier tibetano',

  // GRUPO 4 - Teckels (Dachshunds)
  'Dachshund de pelo corto estándar',
  'Dachshund de pelo largo estándar',
  'Dachshund de pelo duro estándar',
  'Dachshund de pelo corto miniatura',
  'Dachshund de pelo largo miniatura',
  'Dachshund de pelo duro miniatura',
  'Dachshund de pelo corto kaninchen',
  'Dachshund de pelo largo kaninchen',
  'Dachshund de pelo duro kaninchen',

  // GRUPO 5 - Perros tipo Spitz y de tipo primitivo
  'Alaskan Malamute',
  'Husky siberiano',
  'Samoyedo',
  'Spitz alemán enano (Pomerania)',
  'Spitz alemán pequeño',
  'Spitz alemán mediano',
  'Spitz alemán grande',
  'Spitz alemán lobo',
  'Spitz japonés',
  'Spitz finlandés',
  'Spitz noruego (Norsk Buhund)',
  'Perro de los Lapones finlandés',
  'Perro de los Lapones sueco',
  'Perro de los Lapones de Laponia',
  'Perro de Groenlandia',
  'Perro de Canadá (Canadian Eskimo Dog)',
  'Perro de Groenlandia',
  'Elkhound noruego gris',
  'Elkhound noruego negro',
  'Elkhound sueco (Jämthund)',
  'Perro de oso de Carelia',
  'Laika de Siberia occidental',
  'Laika de Siberia oriental',
  'Laika ruso-europeo',
  'Shiba Inu',
  'Shikoku',
  'Hokkaido',
  'Kishu',
  'Kai',
  'Basenji',
  'Canaan Dog',
  'Pharaoh Hound (Podenco faraónico)',
  'Podenco ibicenco',
  'Podenco portugués',
  'Podenco canario',
  'Cirneco dell\'Etna',
  'Perro sin pelo del Perú',
  'Perro sin pelo mexicano (Xoloitzcuintle)',
  'Chow Chow',
  'Eurasier',
  'Shar Pei',
  'Volpino italiano',
  'Keeshond',
  'American Akita',
  'Perro de la isla de Gotland (Gotlandsstövare)',

  // GRUPO 6 - Perros de rastro y razas semejantes
  'Beagle',
  'Beagle Harrier',
  'Harrier',
  'Foxhound americano',
  'Foxhound inglés',
  'Basset Hound',
  'Basset Artesiano de Normandía',
  'Basset Azul de Gascuña',
  'Basset de Bretaña',
  'Basset Fauve de Bretaña',
  'Bloodhound',
  'Coonhound negro y fuego',
  'Grand Bleu de Gascogne',
  'Petit Bleu de Gascogne',
  'Bleu de Gascogne Fauve',
  'Grand Griffon Vendéen',
  'Briquet Griffon Vendéen',
  'Grand Basset Griffon Vendéen',
  'Petit Basset Griffon Vendéen',
  'Billy',
  'Chien Français blanc et noir',
  'Chien Français blanc et orange',
  'Chien Français tricolore',
  'Grand Anglo-Français blanc et noir',
  'Grand Anglo-Français blanc et orange',
  'Grand Anglo-Français tricolore',
  'Poitevin',
  'Porcelaine',
  'Ariégeois',
  'Gascón saintongeois',
  'Perro de Saint-Hubert',
  'Segugio italiano de pelo corto',
  'Segugio italiano de pelo duro',
  'Segugio maremmano',
  'Hamiltonsstövare',
  'Hygenhund',
  'Dunker',
  'Halden Stövare',
  'Schillerstövare',
  'Smålandsstövare',
  'Coonhound de rayas rojas',
  'Plott Hound',
  'Treeing Walker Coonhound',
  'Black and Tan Coonhound',
  'Perro de caza de Bosnia de pelo duro',
  'Braco de Istria de pelo corto',
  'Braco de Istria de pelo duro',
  'Perro montañés de Montenegro',
  'Sabueso de Bosnia',
  'Sabueso de Serbia',
  'Sabueso del Posavec',
  'Sabueso de Transilvania',
  'Sabueso rumano de Carpatos',
  'Sabueso rumano de Mioritic',
  'Sabueso checo',
  'Perro de caza eslovaco',
  'Sabueso polaco',
  'Sabueso alemán',
  'Sabueso de Baviera',
  'Sabueso de Hannover',
  'Sabueso helénico',
  'Rhodesian Ridgeback',
  'Cretan Hound',
  'Sabueso suizo bernés',
  'Sabueso suizo bernés pequeño',
  'Sabueso suizo de Jura',
  'Sabueso suizo de Jura pequeño',
  'Sabueso suizo lucernés',
  'Sabueso suizo lucernés pequeño',
  'Sabueso suizo de Schwyz',
  'Sabueso suizo de Schwyz pequeño',
  'Drever',

  // GRUPO 7 - Perros de muestra
  'Braco alemán de pelo corto',
  'Braco alemán de pelo duro',
  'Braco alemán de pelo largo',
  'Braco de Weimar',
  'Braco de Burgos',
  'Braco español',
  'Braco italiano',
  'Braco húngaro de pelo corto (Vizsla)',
  'Braco húngaro de pelo duro (Vizsla duro)',
  'Braco francés tipo Gascuña',
  'Braco francés tipo Pirineos',
  'Braco de Auvernia',
  'Braco de Bourbonnais',
  'Braco de Ariège',
  'Setter irlandés',
  'Setter irlandés rojo y blanco',
  'Setter inglés',
  'Setter Gordon',
  'Pointer inglés',
  'Pointer inglés de pelo largo (Old Danish)',
  'Épagneul bretón (Bretón)',
  'Épagneul francés',
  'Épagneul de Pont-Audemer',
  'Épagneul Picard',
  'Épagneul azul de Picardía',
  'Perdiguero de Burgos',
  'Perdiguero portugués',
  'Perdiguero de Drente',
  'Perdiguero alemán (Pudelpointer)',
  'Perdiguero de pelo largo alemán (Langhaar)',
  'Perdiguero de pelo duro alemán (Stichelhaar)',
  'Small Münsterländer',
  'Large Münsterländer',
  'Griffón de Korthals',
  'Spinone italiano',
  'Bracco Italiano',
  'Lagotto Romagnolo',
  'Slovenský hrubosrstý stavač',
  'Perro de muestra eslovaco de pelo duro',

  // GRUPO 8 - Perros cobradores de caza, perros de agua y perros levantadores
  'Labrador Retriever',
  'Golden Retriever',
  'Flat Coated Retriever',
  'Curly Coated Retriever',
  'Chesapeake Bay Retriever',
  'Nova Scotia Duck Tolling Retriever',
  'Cocker Spaniel inglés',
  'Cocker Spaniel americano',
  'Springer Spaniel inglés',
  'Springer Spaniel galés',
  'Clumber Spaniel',
  'Field Spaniel',
  'Sussex Spaniel',
  'Irish Water Spaniel',
  'American Water Spaniel',
  'Perro de agua español',
  'Perro de agua portugués',
  'Perro de agua italiano (Lagotto)',
  'Barbet',
  'Boykin Spaniel',
  'Perro de agua frisón',
  'Perro de agua holandés',
  'Perro de agua alemán (Wetterhoun)',
  'Perro de agua de Romagna (Lagotto Romagnolo)',
  'Kooikerhondje',

  // GRUPO 9 - Perros de compañía
  'Bichón frisé',
  'Bichón maltés',
  'Bichón boloñés',
  'Bichón habanero',
  'Bichón de Tenerife',
  'Coton de Tuléar',
  'Löwchen (Pequeño perro león)',
  'Caniche toy',
  'Caniche miniatura',
  'Caniche mediano',
  'Caniche grande',
  'Pug',
  'Bulldog francés',
  'Boston Terrier',
  'Chihuahua de pelo corto',
  'Chihuahua de pelo largo',
  'Papillón',
  'Phalène',
  'Pomerania',
  'Spitz enano',
  'Shih Tzu',
  'Lhasa Apso',
  'Tibet Spaniel',
  'Terrier tibetano',
  'Pekingés',
  'Carlino',
  'King Charles Spaniel',
  'Cavalier King Charles Spaniel',
  'Japanese Chin',
  'Chow Chow',
  'Shar Pei',
  'Perro crestado chino',
  'Affenpinscher',
  'Grifón de Bruselas',
  'Grifón belga',
  'Petit Brabançon',
  'Maltés',
  'Yorkshire Terrier',
  'Silky Terrier australiano',
  'Terrier de juguete inglés',
  'Terrier de juguete ruso',
  'Perro de Faraón miniatura',
  'Bichón de las islas Canarias',
  'Perro de las islas Canarias',

  // GRUPO 10 - Lebreles
  'Galgo español',
  'Galgo afgano',
  'Galgo árabe (Sloughi)',
  'Azawakh',
  'Barzoi (Galgo ruso)',
  'Galgo de Crimea',
  'Galgo irlandés (Irish Wolfhound)',
  'Greyhound',
  'Whippet',
  'Galgo italiano',
  'Scottish Deerhound',
  'Galgo polaco (Chart Polski)',
  'Galgo húngaro (Magyar agár)',
  'Saluki',

  // OTRAS / MISCELÁNEAS
  'Mestizo',
  'Otro',
]

export const razasGato = [
  'Mestizo / Común europeo',
  'Abisinio',
  'American Curl',
  'American Shorthair',
  'American Wirehair',
  'Angora turco',
  'Balinés',
  'Bengalí',
  'Birmano',
  'Bombay',
  'British Longhair',
  'British Shorthair',
  'Burmés',
  'Burmilla',
  'Cornish Rex',
  'Cymric',
  'Devon Rex',
  'Exótico de pelo corto',
  'Gato de los bosques de Noruega',
  'Habana',
  'Himalayo',
  'Japanese Bobtail',
  'Korat',
  'Kurilian Bobtail',
  'LaPerm',
  'Maine Coon',
  'Manx',
  'Munchkin',
  'Neva Masquerade',
  'Noruego del bosque',
  'Ocicat',
  'Oriental de pelo corto',
  'Oriental de pelo largo',
  'Persa',
  'Peterbald',
  'Ragamuffin',
  'Ragdoll',
  'Russian Blue',
  'Savannah',
  'Scottish Fold',
  'Scottish Straight',
  'Selkirk Rex',
  'Siamés',
  'Siberiano',
  'Singapura',
  'Snowshoe',
  'Sokoke',
  'Somali',
  'Sphynx',
  'Tonkinés',
  'Toyger',
  'Van turco',
  'York Chocolate',
  'Otro',
]

export const coloresMascota = [
  'Negro', 'Blanco', 'Marrón', 'Marrón oscuro', 'Marrón claro',
  'Beige', 'Crema', 'Dorado', 'Amarillo', 'Naranja', 'Rojizo',
  'Gris', 'Gris oscuro', 'Gris claro', 'Plateado', 'Atigrado',
  'Negro y blanco', 'Marrón y blanco', 'Negro y marrón',
  'Tricolor', 'Manchado', 'Moteado', 'Ruano', 'Bayo', 'Otro',
]
